"use client";

import { motion } from "motion/react";
import { EASE } from "@/lib/animations";

type Section = {
  id: string;
  title: string;
  intro?: string;
  items: string[];
};

const SECTIONS: Section[] = [
  {
    id: "use-of-platform",
    title: "Use of the Platform",
    items: [
      "Arkive provides tools for organizing trading information, identifying patterns, and generating insights based on user-provided data.",
      "You are responsible for the accuracy of any information uploaded to the platform.",
    ],
  },
  {
    id: "not-financial-advice",
    title: "Not Financial Advice",
    items: [
      "Arkive does not provide financial, investment, tax, or legal advice. Any insights, recommendations, or analytics generated by the platform are provided for informational purposes only.",
      "Users remain solely responsible for all trading and investment decisions.",
    ],
  },
  {
    id: "account-responsibility",
    title: "Account Responsibility",
    items: [
      "You are responsible for maintaining the confidentiality of your account credentials and for all activities performed under your account.",
    ],
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    intro: "You agree not to:",
    items: [
      "Use Arkive for unlawful purposes.",
      "Attempt to gain unauthorized access to systems or data.",
      "Disrupt or interfere with the platform's operation.",
      "Upload malicious software or harmful content.",
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    items: [
      "All platform features, designs, trademarks, and software remain the property of Arkive and its licensors.",
    ],
  },
  {
    id: "termination",
    title: "Termination",
    items: [
      "We reserve the right to suspend or terminate access to Arkive if these Terms are violated.",
    ],
  },
  {
    id: "changes",
    title: "Changes to These Terms",
    items: [
      "We may update these Terms periodically. Continued use of Arkive after changes become effective constitutes acceptance of the updated Terms.",
    ],
  },
  {
    id: "contact",
    title: "Contact",
    items: [
      'Questions regarding these Terms may be directed to <a href="mailto:legal@arkive.ai" class="text-[#3e63dd] hover:underline">legal@arkive.ai</a>.',
    ],
  },
];

function SectionBlock({
  title,
  intro,
  items,
  index,
}: {
  title: string;
  intro?: string;
  items: string[];
  index: number;
}) {
  const isSingle = items.length === 1;
  const isHtml = items[0]?.includes("<a");

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-40px" }}
      transition={{ duration: 0.5, ease: EASE, delay: index * 0.08 }}
      className="flex flex-col gap-4"
    >
      <h2 className="text-[24px] leading-[30px] tracking-[-0.1px] font-medium text-[#141414]">
        {title}
      </h2>
      {intro && (
        <p className="text-sm leading-[20px] font-medium text-[#696e77]">
          {intro}
        </p>
      )}
      {isSingle && isHtml ? (
        <p
          className="text-sm leading-[20px] font-medium text-[#696e77]"
          dangerouslySetInnerHTML={{ __html: items[0] }}
        />
      ) : isSingle ? (
        <p className="text-sm leading-[20px] font-medium text-[#696e77]">
          {items[0]}
        </p>
      ) : intro ? (
        <ul className="flex flex-col">
          {items.map((item, i) => (
            <li
              key={i}
              className="text-sm leading-[20px] font-medium text-[#696e77] pl-4 relative before:content-['•'] before:absolute before:left-0 before:text-[#696e77]"
            >
              {item}
            </li>
          ))}
        </ul>
      ) : (
        <div className="flex flex-col gap-4">
          {items.map((item, i) => {
            const isLastHtml = item.includes("<a");
            return isLastHtml ? (
              <p
                key={i}
                className="text-sm leading-[20px] font-medium text-[#696e77]"
                dangerouslySetInnerHTML={{ __html: item }}
              />
            ) : (
              <p
                key={i}
                className="text-sm leading-[20px] font-medium text-[#696e77]"
              >
                {item}
              </p>
            );
          })}
        </div>
      )}
    </motion.div>
  );
}

export default function TermsContent() {
  return (
    <section className="w-full bg-white">
      <div className="max-w-360 mx-auto px-[clamp(16px,4.17vw,80px)] pb-[clamp(48px,6vw,120px)] pt-[40px]">
        <div className="mx-auto max-w-140 flex flex-col gap-[40px]">
          {/* Intro */}
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-40px" }}
            transition={{ duration: 0.5, ease: EASE }}
            className="text-[24px] leading-[30px] tracking-[-0.1px] font-medium text-[#141414]"
          >
            By accessing or using Arkive, you agree to the following terms.
          </motion.p>

          {SECTIONS.map((section, i) => (
            <SectionBlock
              key={section.id}
              title={section.title}
              intro={section.intro}
              items={section.items}
              index={i}
            />
          ))}
        </div>
      </div>
    </section>
  );
}
